//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatGrafovi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjekatGrafovi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Coordinates.
        /// </summary>
        public static string MainWindow_ChooseCoordinates {
            get {
                return ResourceManager.GetString("MainWindow_ChooseCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose coordinates from file.
        /// </summary>
        public static string MainWindow_CoordinatesText {
            get {
                return ResourceManager.GetString("MainWindow_CoordinatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Form: A,B;B,C;A,C.
        /// </summary>
        public static string MainWindow_CorrectFormEdges {
            get {
                return ResourceManager.GetString("MainWindow_CorrectFormEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Form: A,B,C.
        /// </summary>
        public static string MainWIndow_CorrectFormNodes {
            get {
                return ResourceManager.GetString("MainWIndow_CorrectFormNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge definition:.
        /// </summary>
        public static string MainWindow_EdgeDefinition {
            get {
                return ResourceManager.GetString("MainWindow_EdgeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastGenerate (file).
        /// </summary>
        public static string MainWindow_FastGenerate {
            get {
                return ResourceManager.GetString("MainWindow_FastGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get nodes and edges from file.
        /// </summary>
        public static string MainWindow_FastGenerateText {
            get {
                return ResourceManager.GetString("MainWindow_FastGenerateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string MainWindow_Generate {
            get {
                return ResourceManager.GetString("MainWindow_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Options.
        /// </summary>
        public static string MainWindow_LayoutOptions {
            get {
                return ResourceManager.GetString("MainWindow_LayoutOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes definition:.
        /// </summary>
        public static string MainWindow_NodesDefinition {
            get {
                return ResourceManager.GetString("MainWindow_NodesDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual representation of graphs.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
    }
}
